# **Regras de associação**

## Algoritmo Apriori

In [1]:
import os
from pathlib import Path

import pandas as pd
from apyori import apriori

DRIVE_DIRECTORY = Path.cwd().parent / "data"

## Base de dados mercado 1

In [2]:
df_mercado1 = pd.read_csv(os.path.join(DRIVE_DIRECTORY, "mercado.csv"), header=None)
df_mercado1

          0        1         2         3
0     leite  cerveja       pao  manteiga
1      cafe      pao  manteiga       NaN
2      cafe      pao  manteiga       NaN
3     leite     cafe       pao  manteiga
4   cerveja      NaN       NaN       NaN
5  manteiga      NaN       NaN       NaN
6       pao      NaN       NaN       NaN
7    feijao      NaN       NaN       NaN
8     arroz   feijao       NaN       NaN
9     arroz      NaN       NaN       NaN

In [3]:
transacoes = []
for i in range(len(df_mercado1)):
    transacoes.append([str(df_mercado1.values[i, j]) for j in range(df_mercado1.shape[1])])
transacoes

[['leite', 'cerveja', 'pao', 'manteiga'],
 ['cafe', 'pao', 'manteiga', 'nan'],
 ['cafe', 'pao', 'manteiga', 'nan'],
 ['leite', 'cafe', 'pao', 'manteiga'],
 ['cerveja', 'nan', 'nan', 'nan'],
 ['manteiga', 'nan', 'nan', 'nan'],
 ['pao', 'nan', 'nan', 'nan'],
 ['feijao', 'nan', 'nan', 'nan'],
 ['arroz', 'feijao', 'nan', 'nan'],
 ['arroz', 'nan', 'nan', 'nan']]

In [4]:
regras = apriori(transacoes, min_support=0.3, min_confidence=0.8, min_lift=2)
resultado = list(regras)
resultado

[RelationRecord(items=frozenset({'cafe', 'manteiga'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0)]),
 RelationRecord(items=frozenset({'cafe', 'pao'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'pao'}), confidence=1.0, lift=2.0)]),
 RelationRecord(items=frozenset({'cafe', 'manteiga', 'pao'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'manteiga', 'pao'}), confidence=1.0, lift=2.5), OrderedStatistic(items_base=frozenset({'cafe', 'manteiga'}), items_add=frozenset({'pao'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'cafe', 'pao'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0)])]

In [5]:
len(resultado)

3

In [6]:
resultado[0]

RelationRecord(items=frozenset({'cafe', 'manteiga'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0)])

In [7]:
r = resultado[2][2]
r

[OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'manteiga', 'pao'}), confidence=1.0, lift=2.5),
 OrderedStatistic(items_base=frozenset({'cafe', 'manteiga'}), items_add=frozenset({'pao'}), confidence=1.0, lift=2.0),
 OrderedStatistic(items_base=frozenset({'cafe', 'pao'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0)]

In [8]:
se = []
entao = []
suporte = []
confianca = []
lift = []

for resultados in resultado:
    s = resultados[1]
    result_rules = resultados[2]
    for result_rule in result_rules:
        a = list(result_rule[0])
        b = list(result_rule[1])
        c = result_rule[2]
        l = result_rule[3]

        se.append(a)
        entao.append(b)
        suporte.append(s)
        confianca.append(c)
        lift.append(l)

In [9]:
rules__df = pd.DataFrame({
    'Se': se,
    'Então': entao,
    'Suporte': suporte,
    'Confianca': confianca,
    'Lift': lift
})
rules__df.sort_values(by='Lift', ascending=False)

                 Se            Então  Suporte  Confianca  Lift
2            [cafe]  [manteiga, pao]      0.3        1.0   2.5
0            [cafe]       [manteiga]      0.3        1.0   2.0
1            [cafe]            [pao]      0.3        1.0   2.0
3  [cafe, manteiga]            [pao]      0.3        1.0   2.0
4       [cafe, pao]       [manteiga]      0.3        1.0   2.0

## Base de dados mercado 2